### ISSUE TITLE
Add installation instructions?

### ISSUE THREAD

**Issue by nzfarmer1** [stefanocudini/leaflet-locationpicker#7]
Run npm grunt and bower install
Installed js/jquery libs under js/
Installed leaflet under maps/leaflet

**Comment by nzfarmer1** [comment]
Seems to work fine with just the npm install.

Have added a write up of our use of your plugin here:

https://www.linkedin.com/pulse/adding-leaflet-location-picker-our-node-red-sensor-nodes-mcclure

Thanks for your work.

**Comment by stefanocudini** [comment]
Dear @nzfarmer1 
tnk for you article it's great!

Now from version 0.2.5 the plugin is UMD compatible then support loading by requirejs o commonjs or browserify ecc..

I hope that this improvement simplify the integration on other systems.

Bye Stef
