### ISSUE TITLE
Setting the location to start at location?

### ISSUE THREAD

**Issue by Omar-Aziz** [stefanocudini/leaflet-locationpicker#8]
Right now the location starts at continent level. Is there a way to have it start at a specific location?
So instead of starting in a zoomed out level, I can have it start at specific lat, long, then pick the location?

EDIT: I found it. Changedthe L.latLng inside leaflet-locationpicker.src.js

**Comment by stefanocudini** [comment]
setting value attribute of inpute text!
https://github.com/stefanocudini/leaflet-locationpicker/blob/master/examples/simple.html#L28
